<?php
return array(
    'name'=>'Callcter',
    'URL_MODEL'=>2,
    'URL_HTML_SUFFIX'=>'html|dhtml',
    'MODULE_DENY_LIST'=>array(
    	'Common',
    	'Conf',
    	'Runtime'
    ),
    'DB_TYPE'=>'mysql',
    'DB_USER'=>'root',
    'DB_PWD'=>'%CmX0#cCdHSmR8Qs',
    'DB_HOST'=>'localhost',
    'DB_PORT'=>'3124',
    'DB_NAME'=>'dreamser',
    'DB_CHARSET'=>'utf8',
    'DB_PREFIX'=>'ds_',
    'TEMP_PARSE_STRING'=>array(
        '__PUBLIC__'=>__ROOT__.'/Public'
    ),
    'TEMP_ENGINE_TYPE'=>'PHP'
);